# This file was generated by GoReleaser. DO NOT EDIT.
class Gossm < Formula
  desc "gossm is interactive CLI tool that you select server in AWS and then could connect or send files your AWS server using start-session, ssh, scp under AWS Systems Manger."
  homepage ""
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gjbae1212/gossm/releases/download/v1.1.0/gossm_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "3e3b2df9f8ad6b1d607fd2654917fbf4b7043b1295a8c3dd1e0cdc7e070bfa3b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gjbae1212/gossm/releases/download/v1.1.0/gossm_1.1.0_Linux_x86_64.tar.gz"
      sha256 "5a12ffe8f903d60c688fb5f1d7a58c70163953cbd67c3829e70a8fe6764b6810"
    end
  end

  def install
    bin.install "gossm"
  end
end
