# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  name "gossm"
  desc ""
  homepage ""
  version "1.6.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  on_macos do
    on_intel do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_darwin_amd64.tar.gz"
      sha256 "2b1d4f4f16df9aca1a04f2e934727a7201d12126d58a43a847db72dd9fe96e7c"
    end
    on_arm do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_darwin_arm64.tar.gz"
      sha256 "5f50ed7b7fc02c023ce0cfc29cb3051d38110e5d27c8963ac947e4ac6db68116"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_linux_amd64.tar.gz"
      sha256 "7bd60dacd767329fe79c761c025f4ad3d411d5a4b7d2b1a79dc2ee597be0cc0f"
    end
    on_arm do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_linux_arm64.tar.gz"
      sha256 "76c69a4d4d0b0ac6ea3f6e9e0bc6dc7b837934b35cb07929d10e374af70690f5"
    end
  end

  # No zap stanza required
end
