# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  name "gossm"
  desc ""
  homepage ""
  version "1.6.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  on_macos do
    on_intel do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_darwin_amd64.tar.gz"
      sha256 "579d2b6a9b944c7e59675217686716f805cf2f8443125d8ee1a5379d1346ec05"
    end
    on_arm do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_darwin_arm64.tar.gz"
      sha256 "f17039b140d4ecd2c0f491831b4db7cd4eef2c3bc57382c3e995f2fd9c5e22be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_linux_amd64.tar.gz"
      sha256 "4b20401a1b96b9b7be3069f3a4fe20e1f09d1dc78643ac7a831d13524705f2da"
    end
    on_arm do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_linux_arm64.tar.gz"
      sha256 "13039e732746b0e8882bc0b44d4305cadc110c00f572af4bdf845a35c242cfff"
    end
  end

  # No zap stanza required
end
