# This file was generated by GoReleaser. DO NOT EDIT.
cask "gossm" do
  name "gossm"
  desc ""
  homepage ""
  version "1.6.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gossm"

  on_macos do
    on_intel do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_darwin_amd64.tar.gz"
      sha256 "b452d7b773a573e7721bbc1cb9a7afde6dc9ca608503d6ee9ef142da5748c48a"
    end
    on_arm do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_darwin_arm64.tar.gz"
      sha256 "7d59935b2b1cfc3c75b3110fb52bc8ea7b0edd16c9274a5cacb49cd60a84032f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_linux_amd64.tar.gz"
      sha256 "72ccb9697d116c4e949a1affceeb4e55943e372a48113d499a47c850d0da92ab"
    end
    on_arm do
      url "https://github.com/glieske/gossm/releases/download/v#{version}/gossm_#{version}_linux_arm64.tar.gz"
      sha256 "2686ee052e3d7f26c1adc673501962d1a4f5cd0625dc238a1d12d2673b23224a"
    end
  end

  # No zap stanza required
end
